on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.138.0"
          extended: true

      - name: Build site
        run: hugo --minify

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Copy files via rsync
        run: |
          rsync -avz --delete public/ root@bd8dhf.com:/var/www/bd8dhf/
          ssh root@bd8dhf.com 'chown -R www-data:www-data /var/www/bd8dhf/'